# Generated by Django 2.0.2 on 2018-03-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dst_2013',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=200)),
                ('d1', models.CharField(max_length=200)),
                ('d2', models.CharField(max_length=200)),
                ('d3', models.CharField(max_length=200)),
                ('d4', models.CharField(max_length=200)),
                ('d5', models.CharField(max_length=200)),
                ('d6', models.CharField(max_length=200)),
                ('d7', models.CharField(max_length=200)),
                ('d8', models.CharField(max_length=200)),
                ('d9', models.CharField(max_length=200)),
                ('d10', models.CharField(max_length=200)),
                ('d11', models.CharField(max_length=200)),
                ('d12', models.CharField(max_length=200)),
                ('d13', models.CharField(max_length=200)),
                ('d14', models.CharField(max_length=200)),
                ('d15', models.CharField(max_length=200)),
                ('d16', models.CharField(max_length=200)),
                ('d17', models.CharField(max_length=200)),
                ('d18', models.CharField(max_length=200)),
                ('d19', models.CharField(max_length=200)),
                ('d20', models.CharField(max_length=200)),
                ('d21', models.CharField(max_length=200)),
                ('d22', models.CharField(max_length=200)),
                ('d23', models.CharField(max_length=200)),
                ('d24', models.CharField(max_length=200)),
                ('d25', models.CharField(max_length=200)),
                ('d26', models.CharField(max_length=200)),
                ('d27', models.CharField(max_length=200)),
                ('d28', models.CharField(max_length=200)),
                ('d29', models.CharField(max_length=200)),
                ('d30', models.CharField(max_length=200)),
                ('d31', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='dst_dec2013',
        ),
    ]
